Windows: Fix unresolved symbol atexit() in JIT on MINGW-UCRT
atexit() is used to free some locks for dtoa() kind of functions on program termination.
Since gcc is started with -nostartfiles on JIT compilation this function is not defined:

  C:/msys64/ucrt64/bin/cc.exe -shared -Wfatal-errors -fPIC -shared -w -pipe -O3 -fno-omit-frame-pointer -fno-fast-math -o C:\Users\kanis\AppData\Local\Temp/_ruby_mjit_p13488u2.so -Lc:/Users/kanis/ruby C:\Users\kanis\AppData\Local\Temp/_ruby_mjit_p13488u2.o -lx64-ucrt-ruby310 -lmsvcrt -lgcc -m64 -Wl,--enable-auto-image-base,--enable-auto-import -nostartfiles
  C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/lib/../lib/libmingwex.a(lib64_libmingwex_a-misc.o): in function `dtoa_lock':
  C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/gdtoa/misc.c:84: undefined reference to `atexit'
  collect2.exe: error: ld returned 1 exit status
  compile_c_to_so: failed to link .o to .so: 1

IMHO freeing locks at exit is not relevant for JIT shared objects, so that atexit() is defined as an empty function.